#!/usr/bin/env ruby

require_relative 'CodEngParse.rb'

parser = CodEng.new
if ARGV.length > 0
  if ARGV[0][0] == "/"
    filename = ARGV[0]
  else
    filename = Dir.pwd + '/' + ARGV[0]
  end
  program = File.new(filename).read
  #parser.log(false)
  parser.CodEngParser.parse(program).assess(CEScope.new('root'))
else
  #parser.log(false)
  parser.run
end


